# Generated by Django 5.0.3 on 2024-03-14 16:06

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=20)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(default='+55', max_length=128, region='BR')),
                ('email', models.EmailField(max_length=254)),
                ('divida', models.FloatField()),
                ('endereco', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.FloatField()),
                ('saida', models.FloatField()),
                ('descricao', models.CharField(max_length=50)),
                ('is_agendamento', models.BooleanField(verbose_name=False)),
                ('id_agendamento', models.CharField(blank=True, max_length=3)),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=20)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(default='+55', max_length=128, region='BR')),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=150)),
                ('preco', models.FloatField()),
                ('data_inicio', models.DateTimeField()),
                ('data_final', models.DateTimeField()),
                ('concluido', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.CASCADE, to='salao.cliente')),
                ('funcionario', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.CASCADE, to='salao.funcionario')),
            ],
        ),
    ]
