# Generated by Django 5.0.2 on 2024-03-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='is_agendamento',
            field=models.BooleanField(default=False),
        ),
    ]
