# Generated by Django 5.0.2 on 2024-03-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0002_alter_financeiro_is_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
