# Generated by Django 5.0.1 on 2024-03-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0003_alter_financeiro_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='status',
        ),
    ]
